name: Build and SonarCloud

on:
  push:
    branches:
      - main
      - tp3-start
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: windows-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Donner le droit a Maven Wrapper
        run: chmod +x mvnw
        shell: bash

      - name: Build + Tests + SonarCloud
        run: >
          ./mvnw clean verify sonar:sonar
          -Dsonar.projectKey=poun-2108_TP_3_authentification_forte
          -Dsonar.organization=poun-2108
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
